// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqcsQMjYM4mtqB-iLBIEht9yHNwVGilDM',
    appId: '1:698277792074:web:79b5425a764439cf7c19b3',
    messagingSenderId: '698277792074',
    projectId: 'mania-email',
    authDomain: 'mania-email.firebaseapp.com',
    storageBucket: 'mania-email.appspot.com',
    measurementId: 'G-4F8YF584V4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM5oNlNTSbTJxWKef9UxWHvo8jXdVOPb0',
    appId: '1:698277792074:android:8a30c27eb917a54b7c19b3',
    messagingSenderId: '698277792074',
    projectId: 'mania-email',
    storageBucket: 'mania-email.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDesBG9L0CK1Uben9isvtXz3aGO69lTxHo',
    appId: '1:698277792074:ios:40d758edd4da9d087c19b3',
    messagingSenderId: '698277792074',
    projectId: 'mania-email',
    storageBucket: 'mania-email.appspot.com',
    iosClientId:
        '698277792074-lcjk5aivr2nvv78a8tqcbh6r98lq3o09.apps.googleusercontent.com',
    iosBundleId: 'com.mania.emailClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDesBG9L0CK1Uben9isvtXz3aGO69lTxHo',
    appId: '1:698277792074:ios:40d758edd4da9d087c19b3',
    messagingSenderId: '698277792074',
    projectId: 'mania-email',
    storageBucket: 'mania-email.appspot.com',
    iosClientId:
        '698277792074-lcjk5aivr2nvv78a8tqcbh6r98lq3o09.apps.googleusercontent.com',
    iosBundleId: 'com.mania.emailClient',
  );
}
